In [1]:
import pandas as pd
import glob

pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_columns', None)

In [2]:
files = glob.glob('./*.csv')

df_list = [pd.read_csv(f) for f in files]

In [3]:
results_df = pd.concat(df_list, ignore_index=True)

# leaderboard score
results_df['Leaderboard Score'] = 0.5 * results_df['Retrieval Score'] + 0.5 * results_df['Generation Score (3 released)']

results_df = results_df.sort_values(by=['Leaderboard Score', 'Generation Score (3 released)', 'Retrieval Score'], ascending=False)

results_df.head(10)

,run_id,model_name,text_splitter,chunk_size,chunk_overlap,embedding_cfg,vector_store_cfg,search_cfg,reranker_cfg,model_config,Samples Processed,Processing Time,Samples Per Second,Total,F1@5,Precision@5,Recall@5,Retrieval Score,Correctness (pass rate),Faithfulness (pass rate),Completeness (normalized),Generation Score (3 released),Judge Failures,Leaderboard Score
123,124,api-gpt-oss-120b,TextSplitterWithLineNum,384,64,"{'class': 'OpenAIEmbeddings', 'model': 'api-tgpt-embeddings', 'api_key': 'sk-YUwRq2iW87kSBXBTJN8SFw', 'base_url': 'https://tritonai-api.ucsd.edu', 'check_embedding_ctx_length': False}","{'type': 'faiss', 'batch_size': 32}","{'type': 'mmr', 'k': 15, 'fetch_k': 20, 'lambda_mult': 0.5}","{'class': 'CrossEncoderReranker', 'model_name': 'BAAI/bge-reranker-v2-m3', 'model_kwargs': {'device': 'cpu'}, 'top_n': 8}","{'max_completion_tokens': 2048, 'reasoning_effort': 'high'}",45,16457.98 seconds,0.0,45,0.419489,0.280000,0.927778,0.542422,0.977778,0.977778,0.871111,0.942222,0,0.742322
95,96,api-gpt-oss-120b,TextSplitterWithLineNum,512,64,"{'class': 'OpenAIEmbeddings', 'model': 'api-tgpt-embeddings', 'api_key': 'sk-YUwRq2iW87kSBXBTJN8SFw', 'base_url': 'https://tritonai-api.ucsd.edu', 'check_embedding_ctx_length': False}","{'type': 'faiss', 'batch_size': 32}","{'type': 'mmr', 'k': 18, 'fetch_k': 20, 'lambda_mult': 0.5}","{'class': 'CrossEncoderReranker', 'model_name': 'BAAI/bge-reranker-v2-m3', 'model_kwargs': {'device': 'cpu'}, 'top_n': 8}","{'max_completion_tokens': 2048, 'reasoning_effort': 'high'}",45,17928.45 seconds,0.0,45,0.379630,0.248889,0.916667,0.515062,1.000000,1.000000,0.902222,0.967407,0,0.741235
91,92,api-gpt-oss-120b,TextSplitterWithLineNum,512,64,"{'class': 'OpenAIEmbeddings', 'model': 'api-tgpt-embeddings', 'api_key': 'sk-YUwRq2iW87kSBXBTJN8SFw', 'base_url': 'https://tritonai-api.ucsd.edu', 'check_embedding_ctx_length': False}","{'type': 'faiss', 'batch_size': 32}","{'type': 'mmr', 'k': 15, 'fetch_k': 20, 'lambda_mult': 0.5}","{'class': 'CrossEncoderReranker', 'model_name': 'BAAI/bge-reranker-v2-m3', 'model_kwargs': {'device': 'cpu'}, 'top_n': 8}","{'max_completion_tokens': 2048, 'reasoning_effort': 'high'}",45,18143.50 seconds,0.0,45,0.374250,0.240000,0.938889,0.517713,1.000000,0.977778,0.893333,0.957037,0,0.737375
82,83,api-gpt-oss-120b,TextSplitterWithLineNum,512,64,"{'class': 'OpenAIEmbeddings', 'model': 'api-tgpt-embeddings', 'api_key': 'sk-YUwRq2iW87kSBXBTJN8SFw', 'base_url': 'https://tritonai-api.ucsd.edu', 'check_embedding_ctx_length': False}","{'type': 'faiss', 'batch_size': 32}","{'type': 'similarity', 'k': 10}","{'class': 'CrossEncoderReranker', 'model_name': 'cross-encoder/ms-marco-MiniLM-L12-v2', 'model_kwargs': {'device': 'cpu'}, 'top_n': 8}","{'max_completion_tokens': 2048, 'reasoning_effort': 'high'}",45,18580.15 seconds,0.0,45,0.359788,0.231111,0.916667,0.502522,1.000000,1.000000,0.893333,0.964444,0,0.733483
94,95,api-gpt-oss-120b,TextSplitterWithLineNum,512,64,"{'class': 'OpenAIEmbeddings', 'model': 'api-tgpt-embeddings', 'api_key': 'sk-YUwRq2iW87kSBXBTJN8SFw', 'base_url': 'https://tritonai-api.ucsd.edu', 'check_embedding_ctx_length': False}","{'type': 'faiss', 'batch_size': 32}","{'type': 'mmr', 'k': 18, 'fetch_k': 20, 'lambda_mult': 0.5}","{'class': 'CrossEncoderReranker', 'model_name': 'cross-encoder/ms-marco-MiniLM-L12-v2', 'model_kwargs': {'device': 'cpu'}, 'top_n': 8}","{'max_completion_tokens': 2048, 'reasoning_effort': 'high'}",45,17974.78 seconds,0.0,45,0.352381,0.226667,0.894444,0.491164,0.977778,1.000000,0.862222,0.946667,0,0.718915
127,128,api-gpt-oss-120b,TextSplitterWithLineNum,384,64,"{'class': 'OpenAIEmbeddings', 'model': 'api-tgpt-embeddings', 'api_key': 'sk-YUwRq2iW87kSBXBTJN8SFw', 'base_url': 'https://tritonai-api.ucsd.edu', 'check_embedding_ctx_length': False}","{'type': 'faiss', 'batch_size': 32}","{'type': 'mmr', 'k': 18, 'fetch_k': 20, 'lambda_mult': 0.5}","{'class': 'CrossEncoderReranker', 'model_name': 'BAAI/bge-reranker-v2-m3', 'model_kwargs': {'device': 'cpu'}, 'top_n': 8}","{'max_completion_tokens': 2048, 'reasoning_effort': 'high'}",45,16258.47 seconds,0.0,45,0.380600,0.257778,0.838889,0.492422,0.977778,0.977778,0.871111,0.942222,0,0.717322
59,60,api-mistral-small-3.2-2506,TextSplitterWithLineNum,384,64,"{'class': 'OpenAIEmbeddings', 'model': 'api-tgpt-embeddings', 'api_key': 'sk-YUwRq2iW87kSBXBTJN8SFw', 'base_url': 'https://tritonai-api.ucsd.edu', 'check_embedding_ctx_length': False}","{'type': 'faiss', 'batch_size': 32}","{'type': 'mmr', 'k': 15, 'fetch_k': 20, 'lambda_mult': 0.5}","{'class': 'CrossEncoderReranker', 'model_name': 'BAAI/bge-reranker-v2-m3', 'model_kwargs': {'device': 'cpu'}, 'top_n': 8}","{'max_completion_tokens': 2048, 'reasoning_effort': 'high'}",45,19706.74 seconds,0.0,45,0.376102,0.244444,0.916667,0.512404,0.977778,0.977778,0.808889,0.921481,0,0.716943
63,64,api-mistral-small-3.2-2506,TextSplitterWithLineNum,384,64,"{'class': 'OpenAIEmbeddings', 'model': 'api-tgpt-embeddings', 'api_key': 'sk-YUwRq2iW87kSBXBTJN8SFw', 'base_url': 'https://tritonai-api.ucsd.edu', 'check_embedding_ctx_length': False}","{'type': 'faiss', 'batch_size': 32}","{'type': 'mmr', 'k': 18, 'fetch_k': 20, 'lambda_mult': 0.5}","{'class': 'CrossEncoderReranker', 'model_name': 'BAAI/bge-reranker-v2-m3', 'model_kwargs': {'device': 'cpu'}, 'top_n': 8}","{'max_completion_tokens': 2048, 'reasoning_effort': 'high'}",45,19581.02 seconds,0.0,45,0.362081,0.235556,0.894444,0.497360,0.977778,1.000000,0.826667,0.934815,0,0.716088
83,84,api-gpt-oss-120b,TextSplitterWithLineNum,512,64,"{'class': 'OpenAIEmbeddings', 'model': 'api-tgpt-embeddings', 'api_key': 'sk-YUwRq2iW87kSBXBTJN8SFw', 'base_url': 'https://tritonai-api.ucsd.edu', 'check_embedding_ctx_length': False}","{'type': 'faiss', 'batch_size': 32}","{'type': 'similarity', 'k': 10}","{'class': 'CrossEncoderReranker', 'model_name': 'BAAI/bge-reranker-v2-m3', 'model_kwargs': {'device': 'cpu'}, 'top_n': 8}","{'max_completion_tokens': 2048, 'reasoning_effort': 'high'}",45,18536.87 seconds,0.0,45,0.354850,0.231111,0.883333,0.489765,0.977778,0.977778,0.871111,0.942222,0,0.715994
19,20,api-mistral-small-3.2-2506,TextSplitterWithLineNum,512,64,"{'class': 'OpenAIEmbeddings', 'model': 'api-tgpt-embeddings', 'api_key': 'sk-YUwRq2iW87kSBXBTJN8SFw', 'base_url': 'https://tritonai-api.ucsd.edu', 'check_embedding_ctx_length': False}","{'type': 'faiss', 'batch_size': 32}","{'type': 'similarity', 'k': 10}","{'class': 'CrossEncoderReranker', 'model_name': 'BAAI/bge-reranker-v2-m3', 'model_kwargs': {'device': 'cpu'}, 'top_n': 8}","{'max_completion_tokens': 2048, 'reasoning_effort': 'high'}",45,21012.06 seconds,0.0,45,0.343563,0.217778,0.894444,0.485262,1.000000,1.000000,0.831111,0.943704,0,0.714483

In [4]:
import ast

def parse_cfg(x):
    if isinstance(x, dict):
        return x
    if isinstance(x, str):
        return ast.literal_eval(x)
    return {}

In [5]:
search_cfg = results_df['search_cfg'].apply(parse_cfg)
embedding_cfg = results_df['embedding_cfg'].apply(parse_cfg)
reranker_cfg = results_df['reranker_cfg'].apply(parse_cfg)

results_df['search_type'] = search_cfg.apply(lambda x: x.get('type'))
results_df['search_k'] = search_cfg.apply(lambda x: x.get('k'))
results_df['embedding_class'] = embedding_cfg.apply(lambda x: x.get('class'))
results_df['embedding_model'] = embedding_cfg.apply(lambda x: x.get('model'))
results_df['reranker_class'] = reranker_cfg.apply(lambda x: x.get('class'))
results_df['reranker_model'] = reranker_cfg.apply(lambda x: x.get('model_name'))
results_df['reranker_top_n'] = reranker_cfg.apply(lambda x: x.get('top_n'))

results_df.drop(['search_cfg', 'embedding_cfg', 'reranker_cfg'], axis=1, inplace=True)

# different model everything else same
results_df[
    (results_df['chunk_size'] == 512) & 
    (results_df['search_type'] == 'similarity') &
    (results_df['search_k'] == 10) &
    (results_df['embedding_class'] == 'OpenAIEmbeddings') &
    (results_df['reranker_class'] == 'CrossEncoderReranker') &
    (results_df['reranker_model'] == 'cross-encoder/ms-marco-MiniLM-L6-v2')
]

,run_id,model_name,text_splitter,chunk_size,chunk_overlap,vector_store_cfg,model_config,Samples Processed,Processing Time,Samples Per Second,Total,F1@5,Precision@5,Recall@5,Retrieval Score,Correctness (pass rate),Faithfulness (pass rate),Completeness (normalized),Generation Score (3 released),Judge Failures,Leaderboard Score,search_type,search_k,embedding_class,embedding_model,reranker_class,reranker_model,reranker_top_n
17,18,api-mistral-small-3.2-2506,TextSplitterWithLineNum,512,64,"{'type': 'faiss', 'batch_size': 32}","{'max_completion_tokens': 2048, 'reasoning_effort': 'high'}",45,21062.52 seconds,0.00,45,0.347795,0.222222,0.883333,0.484450,1.000000,1.000000,0.813333,0.937778,0,0.711114,similarity,10,OpenAIEmbeddings,api-tgpt-embeddings,CrossEncoderReranker,cross-encoder/ms-marco-MiniLM-L6-v2,8
81,82,api-gpt-oss-120b,TextSplitterWithLineNum,512,64,"{'type': 'faiss', 'batch_size': 32}","{'max_completion_tokens': 2048, 'reasoning_effort': 'high'}",45,18615.23 seconds,0.00,45,0.361905,0.235556,0.883333,0.493598,0.955556,0.955556,0.844444,0.918519,0,0.706058,similarity,10,OpenAIEmbeddings,api-tgpt-embeddings,CrossEncoderReranker,cross-encoder/ms-marco-MiniLM-L6-v2,8
80,81,api-gpt-oss-120b,TextSplitterWithLineNum,512,64,"{'type': 'faiss', 'batch_size': 32}","{'max_completion_tokens': 2048, 'reasoning_effort': 'high'}",45,18655.34 seconds,0.00,45,0.306878,0.195556,0.805556,0.435996,0.955556,0.955556,0.831111,0.914074,0,0.675035,similarity,10,OpenAIEmbeddings,api-tgpt-embeddings,CrossEncoderReranker,cross-encoder/ms-marco-MiniLM-L6-v2,5
16,17,api-mistral-small-3.2-2506,TextSplitterWithLineNum,512,64,"{'type': 'faiss', 'batch_size': 32}","{'max_completion_tokens': 2048, 'reasoning_effort': 'high'}",45,21084.66 seconds,0.00,45,0.316049,0.200000,0.827778,0.447942,0.911111,0.955556,0.791111,0.885926,0,0.666934,similarity,10,OpenAIEmbeddings,api-tgpt-embeddings,CrossEncoderReranker,cross-encoder/ms-marco-MiniLM-L6-v2,5
132,5,api-mistral-small-3.2-2506,TextSplitterWithLineNum,512,64,"{'type': 'faiss', 'batch_size': 32}","{'max_completion_tokens': 2048, 'reasoning_effort': 'high'}",45,2118.08 seconds,0.02,45,0.288536,0.177778,0.816667,0.427660,0.933333,0.955556,0.782222,0.890370,0,0.659015,similarity,10,OpenAIEmbeddings,api-tgpt-embeddings,CrossEncoderReranker,cross-encoder/ms-marco-MiniLM-L6-v2,5
140,13,api-gpt-oss-120b,TextSplitterWithLineNum,512,64,"{'type': 'faiss', 'batch_size': 32}","{'max_completion_tokens': 2048, 'reasoning_effort': 'high'}",45,1845.82 seconds,0.02,45,0.284303,0.177778,0.772222,0.411434,0.933333,0.977778,0.791111,0.900741,0,0.656088,similarity,10,OpenAIEmbeddings,api-tgpt-embeddings,CrossEncoderReranker,cross-encoder/ms-marco-MiniLM-L6-v2,5
146,3,api-mistral-small-3.2-2506,TextSplitterWithLineNum,512,64,"{'type': 'faiss', 'batch_size': 32}","{'max_completion_tokens': 2048, 'reasoning_effort': 'high'}",45,3015.97 seconds,0.01,45,0.286420,0.177778,0.794444,0.419547,0.933333,0.955556,0.768889,0.885926,0,0.652737,similarity,10,OpenAIEmbeddings,api-tgpt-embeddings,CrossEncoderReranker,cross-encoder/ms-marco-MiniLM-L6-v2,5
158,19,api-gemma-4-26b,TextSplitterWithLineNum,512,64,"{'type': 'faiss', 'batch_size': 32}","{'max_completion_tokens': 2048, 'reasoning_effort': 'high'}",45,2380.36 seconds,0.02,45,0.095238,0.057778,0.277778,0.143598,0.866667,0.933333,0.724444,0.841481,0,0.492540,similarity,10,OpenAIEmbeddings,api-tgpt-embeddings,CrossEncoderReranker,cross-encoder/ms-marco-MiniLM-L6-v2,5

In [6]:
# different embeddings everything else same
results_df[
    (results_df['chunk_size'] == 512) & 
    (results_df['search_type'] == 'similarity') &
    (results_df['search_k'] == 10) &
    (results_df['model_name'] == 'api-mistral-small-3.2-2506') &
    (results_df['reranker_class'] == 'CrossEncoderReranker') &
    (results_df['reranker_model'] == 'cross-encoder/ms-marco-MiniLM-L6-v2')
]

,run_id,model_name,text_splitter,chunk_size,chunk_overlap,vector_store_cfg,model_config,Samples Processed,Processing Time,Samples Per Second,Total,F1@5,Precision@5,Recall@5,Retrieval Score,Correctness (pass rate),Faithfulness (pass rate),Completeness (normalized),Generation Score (3 released),Judge Failures,Leaderboard Score,search_type,search_k,embedding_class,embedding_model,reranker_class,reranker_model,reranker_top_n
17,18,api-mistral-small-3.2-2506,TextSplitterWithLineNum,512,64,"{'type': 'faiss', 'batch_size': 32}","{'max_completion_tokens': 2048, 'reasoning_effort': 'high'}",45,21062.52 seconds,0.00,45,0.347795,0.222222,0.883333,0.484450,1.000000,1.000000,0.813333,0.937778,0,0.711114,similarity,10,OpenAIEmbeddings,api-tgpt-embeddings,CrossEncoderReranker,cross-encoder/ms-marco-MiniLM-L6-v2,8
16,17,api-mistral-small-3.2-2506,TextSplitterWithLineNum,512,64,"{'type': 'faiss', 'batch_size': 32}","{'max_completion_tokens': 2048, 'reasoning_effort': 'high'}",45,21084.66 seconds,0.00,45,0.316049,0.200000,0.827778,0.447942,0.911111,0.955556,0.791111,0.885926,0,0.666934,similarity,10,OpenAIEmbeddings,api-tgpt-embeddings,CrossEncoderReranker,cross-encoder/ms-marco-MiniLM-L6-v2,5
132,5,api-mistral-small-3.2-2506,TextSplitterWithLineNum,512,64,"{'type': 'faiss', 'batch_size': 32}","{'max_completion_tokens': 2048, 'reasoning_effort': 'high'}",45,2118.08 seconds,0.02,45,0.288536,0.177778,0.816667,0.427660,0.933333,0.955556,0.782222,0.890370,0,0.659015,similarity,10,OpenAIEmbeddings,api-tgpt-embeddings,CrossEncoderReranker,cross-encoder/ms-marco-MiniLM-L6-v2,5
146,3,api-mistral-small-3.2-2506,TextSplitterWithLineNum,512,64,"{'type': 'faiss', 'batch_size': 32}","{'max_completion_tokens': 2048, 'reasoning_effort': 'high'}",45,3015.97 seconds,0.01,45,0.286420,0.177778,0.794444,0.419547,0.933333,0.955556,0.768889,0.885926,0,0.652737,similarity,10,OpenAIEmbeddings,api-tgpt-embeddings,CrossEncoderReranker,cross-encoder/ms-marco-MiniLM-L6-v2,5
1,2,api-mistral-small-3.2-2506,TextSplitterWithLineNum,512,64,"{'type': 'faiss', 'batch_size': 32}","{'max_completion_tokens': 2048, 'reasoning_effort': 'high'}",45,21704.51 seconds,0.00,45,0.304762,0.195556,0.783333,0.427884,0.888889,0.955556,0.751111,0.865185,0,0.646534,similarity,10,HuggingFaceEmbeddings,None,CrossEncoderReranker,cross-encoder/ms-marco-MiniLM-L6-v2,8
0,1,api-mistral-small-3.2-2506,TextSplitterWithLineNum,512,64,"{'type': 'faiss', 'batch_size': 32}","{'max_completion_tokens': 2048, 'reasoning_effort': 'high'}",45,21735.43 seconds,0.00,45,0.261023,0.164444,0.694444,0.373304,0.888889,1.000000,0.764444,0.884444,0,0.628874,similarity,10,HuggingFaceEmbeddings,None,CrossEncoderReranker,cross-encoder/ms-marco-MiniLM-L6-v2,5
144,1,api-mistral-small-3.2-2506,TextSplitterWithLineNum,512,64,"{'type': 'faiss', 'batch_size': 32}","{'max_completion_tokens': 2048, 'reasoning_effort': 'high'}",45,3074.85 seconds,0.01,45,0.256790,0.160000,0.705556,0.374115,0.866667,0.977778,0.768889,0.871111,0,0.622613,similarity,10,HuggingFaceEmbeddings,None,CrossEncoderReranker,cross-encoder/ms-marco-MiniLM-L6-v2,5
128,1,api-mistral-small-3.2-2506,TextSplitterWithLineNum,512,64,"{'type': 'faiss', 'batch_size': 32}","{'max_completion_tokens': 2048, 'reasoning_effort': 'high'}",45,2232.16 seconds,0.02,45,0.249383,0.155556,0.683333,0.362757,0.866667,0.977778,0.733333,0.859259,0,0.611008,similarity,10,HuggingFaceEmbeddings,None,CrossEncoderReranker,cross-encoder/ms-marco-MiniLM-L6-v2,5