In [1]:
import pandas as pd
import glob

pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_columns', None)

In [2]:
files = glob.glob('./*.csv')

df_list = [pd.read_csv(f) for f in files]

In [3]:
results_df = pd.concat(df_list, ignore_index=True)

results_df = results_df.sort_values(by=['Correctness (pass rate)', 'Faithfulness (pass rate)', 
                                        'F1@5', 'Precision@5', 'Recall@5', 'Retrieval Score'], ascending=False)

results_df.head(5)

,run_id,model_name,text_splitter,chunk_size,chunk_overlap,embedding_cfg,vector_store_cfg,search_cfg,reranker_cfg,model_config,Samples Processed,Processing Time,Samples Per Second,Total,F1@5,Precision@5,Recall@5,Retrieval Score,Correctness (pass rate),Faithfulness (pass rate),Completeness (normalized),Generation Score (3 released),Judge Failures
5,6,api-mistral-small-3.2-2506,TextSplitterWithLineNum,512,64,"{'class': 'OpenAIEmbeddings', 'model': 'api-tgpt-embeddings', 'api_key': 'sk-YUwRq2iW87kSBXBTJN8SFw', 'base_url': 'https://tritonai-api.ucsd.edu', 'check_embedding_ctx_length': False}","{'type': 'faiss', 'batch_size': 32}","{'type': 'similarity', 'k': 10}","{'class': 'CrossEncoderReranker', 'model_name': 'cross-encoder/ms-marco-MiniLM-L12-v2', 'model_kwargs': {'device': 'cpu'}, 'top_n': 5}","{'max_completion_tokens': 2048, 'reasoning_effort': 'high'}",45,2095.15 seconds,0.02,45,0.289594,0.177778,0.827778,0.431717,0.977778,0.977778,0.800000,0.918519,0
13,14,api-gpt-oss-120b,TextSplitterWithLineNum,512,64,"{'class': 'OpenAIEmbeddings', 'model': 'api-tgpt-embeddings', 'api_key': 'sk-YUwRq2iW87kSBXBTJN8SFw', 'base_url': 'https://tritonai-api.ucsd.edu', 'check_embedding_ctx_length': False}","{'type': 'faiss', 'batch_size': 32}","{'type': 'similarity', 'k': 10}","{'class': 'CrossEncoderReranker', 'model_name': 'cross-encoder/ms-marco-MiniLM-L12-v2', 'model_kwargs': {'device': 'cpu'}, 'top_n': 5}","{'max_completion_tokens': 2048, 'reasoning_effort': 'high'}",45,1805.74 seconds,0.02,45,0.279012,0.173333,0.772222,0.408189,0.977778,0.977778,0.862222,0.939259,0
14,15,api-gpt-oss-120b,TextSplitterWithLineNum,512,64,"{'class': 'OpenAIEmbeddings', 'model': 'api-tgpt-embeddings', 'api_key': 'sk-YUwRq2iW87kSBXBTJN8SFw', 'base_url': 'https://tritonai-api.ucsd.edu', 'check_embedding_ctx_length': False}","{'type': 'faiss', 'batch_size': 32}","{'type': 'mmr', 'k': 10, 'fetch_k': 20, 'lambda_mult': 0.5}","{'class': 'CrossEncoderReranker', 'model_name': 'cross-encoder/ms-marco-MiniLM-L6-v2', 'model_kwargs': {'device': 'cpu'}, 'top_n': 5}","{'max_completion_tokens': 2048, 'reasoning_effort': 'high'}",45,1760.05 seconds,0.03,45,0.314638,0.200000,0.822222,0.445620,0.955556,0.977778,0.835556,0.922963,0
15,16,api-gpt-oss-120b,TextSplitterWithLineNum,512,64,"{'class': 'OpenAIEmbeddings', 'model': 'api-tgpt-embeddings', 'api_key': 'sk-YUwRq2iW87kSBXBTJN8SFw', 'base_url': 'https://tritonai-api.ucsd.edu', 'check_embedding_ctx_length': False}","{'type': 'faiss', 'batch_size': 32}","{'type': 'mmr', 'k': 10, 'fetch_k': 20, 'lambda_mult': 0.5}","{'class': 'CrossEncoderReranker', 'model_name': 'cross-encoder/ms-marco-MiniLM-L12-v2', 'model_kwargs': {'device': 'cpu'}, 'top_n': 5}","{'max_completion_tokens': 2048, 'reasoning_effort': 'high'}",45,1713.76 seconds,0.03,45,0.271605,0.168889,0.750000,0.396831,0.955556,0.977778,0.831111,0.921481,0
6,7,api-mistral-small-3.2-2506,TextSplitterWithLineNum,512,64,"{'class': 'OpenAIEmbeddings', 'model': 'api-tgpt-embeddings', 'api_key': 'sk-YUwRq2iW87kSBXBTJN8SFw', 'base_url': 'https://tritonai-api.ucsd.edu', 'check_embedding_ctx_length': False}","{'type': 'faiss', 'batch_size': 32}","{'type': 'mmr', 'k': 10, 'fetch_k': 20, 'lambda_mult': 0.5}","{'class': 'CrossEncoderReranker', 'model_name': 'cross-encoder/ms-marco-MiniLM-L6-v2', 'model_kwargs': {'device': 'cpu'}, 'top_n': 5}","{'max_completion_tokens': 2048, 'reasoning_effort': 'high'}",45,2069.88 seconds,0.02,45,0.312875,0.195556,0.850000,0.452810,0.933333,1.000000,0.764444,0.899259,0

In [4]:
print(len(results_df))
print('-' * 100)
print(results_df['model_name'].value_counts())
print('-' * 100)
print(results_df['chunk_size'].value_counts())
print('-' * 100)
print(results_df['embedding_cfg'].value_counts())
print('-' * 100)
print(results_df['search_cfg'].value_counts())

33
----------------------------------------------------------------------------------------------------
model_name
api-mistral-small-3.2-2506    16
api-gemma-4-26b                9
api-gpt-oss-120b               8
Name: count, dtype: int64
----------------------------------------------------------------------------------------------------
chunk_size
512     25
1024     8
Name: count, dtype: int64
----------------------------------------------------------------------------------------------------
embedding_cfg
{'class': 'OpenAIEmbeddings', 'model': 'api-tgpt-embeddings', 'api_key': 'sk-YUwRq2iW87kSBXBTJN8SFw', 'base_url': 'https://tritonai-api.ucsd.edu', 'check_embedding_ctx_length': False}             18
{'class': 'HuggingFaceEmbeddings', 'model_name': 'sentence-transformers/all-MiniLM-L6-v2', 'model_kwargs': {'device': 'cpu'}, 'encode_kwargs': {'normalize_embeddings': True, 'batch_size': 32}}    15
Name: count, dtype: int64
----------------------------------------------------------------------------------------------------
search_cfg
{'type': 'similarity', 'k': 10}                                18
{'type': 'mmr', 'k': 10, 'fetch_k': 20, 'lambda_mult': 0.5}    15
Name: count, dtype: int64

In [5]:
import ast

def parse_cfg(x):
    if isinstance(x, dict):
        return x
    if isinstance(x, str):
        return ast.literal_eval(x)
    return {}

In [6]:
search_cfg = results_df['search_cfg'].apply(parse_cfg)
embedding_cfg = results_df['embedding_cfg'].apply(parse_cfg)
reranker_cfg = results_df['reranker_cfg'].apply(parse_cfg)

results_df['search_type'] = search_cfg.apply(lambda x: x.get('type'))
results_df['search_k'] = search_cfg.apply(lambda x: x.get('k'))
results_df['embedding_class'] = embedding_cfg.apply(lambda x: x.get('class'))
results_df['embedding_model'] = embedding_cfg.apply(lambda x: x.get('model'))
results_df['reranker_class'] = reranker_cfg.apply(lambda x: x.get('class'))
results_df['reranker_model'] = reranker_cfg.apply(lambda x: x.get('model_name'))

results_df.drop(['search_cfg', 'embedding_cfg', 'reranker_cfg'], axis=1, inplace=True)

# different model everything else same
results_df[
    (results_df['chunk_size'] == 512) & 
    (results_df['search_type'] == 'similarity') &
    (results_df['search_k'] == 10) &
    (results_df['embedding_class'] == 'OpenAIEmbeddings') &
    (results_df['reranker_class'] == 'CrossEncoderReranker') &
    (results_df['reranker_model'] == 'cross-encoder/ms-marco-MiniLM-L6-v2')
]

,run_id,model_name,text_splitter,chunk_size,chunk_overlap,vector_store_cfg,model_config,Samples Processed,Processing Time,Samples Per Second,Total,F1@5,Precision@5,Recall@5,Retrieval Score,Correctness (pass rate),Faithfulness (pass rate),Completeness (normalized),Generation Score (3 released),Judge Failures,search_type,search_k,embedding_class,embedding_model,reranker_class,reranker_model
12,13,api-gpt-oss-120b,TextSplitterWithLineNum,512,64,"{'type': 'faiss', 'batch_size': 32}","{'max_completion_tokens': 2048, 'reasoning_effort': 'high'}",45,1845.82 seconds,0.02,45,0.284303,0.177778,0.772222,0.411434,0.933333,0.977778,0.791111,0.900741,0,similarity,10,OpenAIEmbeddings,api-tgpt-embeddings,CrossEncoderReranker,cross-encoder/ms-marco-MiniLM-L6-v2
4,5,api-mistral-small-3.2-2506,TextSplitterWithLineNum,512,64,"{'type': 'faiss', 'batch_size': 32}","{'max_completion_tokens': 2048, 'reasoning_effort': 'high'}",45,2118.08 seconds,0.02,45,0.288536,0.177778,0.816667,0.427660,0.933333,0.955556,0.782222,0.890370,0,similarity,10,OpenAIEmbeddings,api-tgpt-embeddings,CrossEncoderReranker,cross-encoder/ms-marco-MiniLM-L6-v2
18,3,api-mistral-small-3.2-2506,TextSplitterWithLineNum,512,64,"{'type': 'faiss', 'batch_size': 32}","{'max_completion_tokens': 2048, 'reasoning_effort': 'high'}",45,3015.97 seconds,0.01,45,0.286420,0.177778,0.794444,0.419547,0.933333,0.955556,0.768889,0.885926,0,similarity,10,OpenAIEmbeddings,api-tgpt-embeddings,CrossEncoderReranker,cross-encoder/ms-marco-MiniLM-L6-v2
30,19,api-gemma-4-26b,TextSplitterWithLineNum,512,64,"{'type': 'faiss', 'batch_size': 32}","{'max_completion_tokens': 2048, 'reasoning_effort': 'high'}",45,2380.36 seconds,0.02,45,0.095238,0.057778,0.277778,0.143598,0.866667,0.933333,0.724444,0.841481,0,similarity,10,OpenAIEmbeddings,api-tgpt-embeddings,CrossEncoderReranker,cross-encoder/ms-marco-MiniLM-L6-v2

In [7]:
# different embeddings everything else same
results_df[
    (results_df['chunk_size'] == 512) & 
    (results_df['search_type'] == 'similarity') &
    (results_df['search_k'] == 10) &
    (results_df['model_name'] == 'api-mistral-small-3.2-2506') &
    (results_df['reranker_class'] == 'CrossEncoderReranker') &
    (results_df['reranker_model'] == 'cross-encoder/ms-marco-MiniLM-L6-v2')
]

,run_id,model_name,text_splitter,chunk_size,chunk_overlap,vector_store_cfg,model_config,Samples Processed,Processing Time,Samples Per Second,Total,F1@5,Precision@5,Recall@5,Retrieval Score,Correctness (pass rate),Faithfulness (pass rate),Completeness (normalized),Generation Score (3 released),Judge Failures,search_type,search_k,embedding_class,embedding_model,reranker_class,reranker_model
4,5,api-mistral-small-3.2-2506,TextSplitterWithLineNum,512,64,"{'type': 'faiss', 'batch_size': 32}","{'max_completion_tokens': 2048, 'reasoning_effort': 'high'}",45,2118.08 seconds,0.02,45,0.288536,0.177778,0.816667,0.427660,0.933333,0.955556,0.782222,0.890370,0,similarity,10,OpenAIEmbeddings,api-tgpt-embeddings,CrossEncoderReranker,cross-encoder/ms-marco-MiniLM-L6-v2
18,3,api-mistral-small-3.2-2506,TextSplitterWithLineNum,512,64,"{'type': 'faiss', 'batch_size': 32}","{'max_completion_tokens': 2048, 'reasoning_effort': 'high'}",45,3015.97 seconds,0.01,45,0.286420,0.177778,0.794444,0.419547,0.933333,0.955556,0.768889,0.885926,0,similarity,10,OpenAIEmbeddings,api-tgpt-embeddings,CrossEncoderReranker,cross-encoder/ms-marco-MiniLM-L6-v2
16,1,api-mistral-small-3.2-2506,TextSplitterWithLineNum,512,64,"{'type': 'faiss', 'batch_size': 32}","{'max_completion_tokens': 2048, 'reasoning_effort': 'high'}",45,3074.85 seconds,0.01,45,0.256790,0.160000,0.705556,0.374115,0.866667,0.977778,0.768889,0.871111,0,similarity,10,HuggingFaceEmbeddings,None,CrossEncoderReranker,cross-encoder/ms-marco-MiniLM-L6-v2
0,1,api-mistral-small-3.2-2506,TextSplitterWithLineNum,512,64,"{'type': 'faiss', 'batch_size': 32}","{'max_completion_tokens': 2048, 'reasoning_effort': 'high'}",45,2232.16 seconds,0.02,45,0.249383,0.155556,0.683333,0.362757,0.866667,0.977778,0.733333,0.859259,0,similarity,10,HuggingFaceEmbeddings,None,CrossEncoderReranker,cross-encoder/ms-marco-MiniLM-L6-v2